//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_Murtazin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class kit_online_id
    {
        public string vending_machine_id { get; set; }
        public string kit_online_id1 { get; set; }
        public string company { get; set; }
        public string payment_type { get; set; }
        public string critical_threshold_template { get; set; }
        public string service_priority { get; set; }
        public string manager { get; set; }
        public string status { get; set; }
        public string notification_template { get; set; }
        public string working_hours { get; set; }
        public string engineer { get; set; }
    
        public virtual companies companies { get; set; }
        public virtual critical_threshold_templates critical_threshold_templates { get; set; }
        public virtual notification_templates notification_templates { get; set; }
        public virtual payment_types payment_types { get; set; }
        public virtual service_priorities service_priorities { get; set; }
        public virtual statuss statuss { get; set; }
        public virtual users users { get; set; }
        public virtual users users1 { get; set; }
        public virtual vending_machines vending_machines { get; set; }
    }
}
