//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_Murtazin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class maintenance
    {
        public double maintenance_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string issues_found { get; set; }
        public string vending_machine_id { get; set; }
        public string user_id { get; set; }
        public string work_description { get; set; }
    
        public virtual users users { get; set; }
        public virtual vending_machines vending_machines { get; set; }
        public virtual work_descriptions work_descriptions { get; set; }
    }
}
