//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_Murtazin.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UP_MurtazinEntities : DbContext
    {
        public UP_MurtazinEntities()
            : base("name=UP_MurtazinEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<companies> companies { get; set; }
        public DbSet<critical_threshold_templates> critical_threshold_templates { get; set; }
        public DbSet<kit_online_id> kit_online_id { get; set; }
        public DbSet<maintenance> maintenance { get; set; }
        public DbSet<notification_templates> notification_templates { get; set; }
        public DbSet<operators> operators { get; set; }
        public DbSet<payment_methods> payment_methods { get; set; }
        public DbSet<payment_types> payment_types { get; set; }
        public DbSet<product> product { get; set; }
        public DbSet<rfid_cash_collections> rfid_cash_collections { get; set; }
        public DbSet<rfid_loading> rfid_loading { get; set; }
        public DbSet<rfid_services> rfid_services { get; set; }
        public DbSet<roles> roles { get; set; }
        public DbSet<sales> sales { get; set; }
        public DbSet<service_priorities> service_priorities { get; set; }
        public DbSet<statuss> statuss { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<users> users { get; set; }
        public DbSet<vending_machines> vending_machines { get; set; }
        public DbSet<work_descriptions> work_descriptions { get; set; }
        public DbSet<work_modes> work_modes { get; set; }
    }
}
