//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_Murtazin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class operators
    {
        public operators()
        {
            this.vending_machines = new HashSet<vending_machines>();
        }
    
        public string @operator { get; set; }
    
        public virtual ICollection<vending_machines> vending_machines { get; set; }
    }
}
