//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_Murtazin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_methods
    {
        public payment_methods()
        {
            this.sales = new HashSet<sales>();
        }
    
        public string payment_method { get; set; }
    
        public virtual ICollection<sales> sales { get; set; }
    }
}
