//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_Murtazin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.sales = new HashSet<sales>();
        }
    
        public string product_id { get; set; }
        public string name { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> min_stock { get; set; }
        public string vending_machine_id { get; set; }
        public string description { get; set; }
        public Nullable<double> quantity_available { get; set; }
        public Nullable<double> sales_trend { get; set; }
    
        public virtual vending_machines vending_machines { get; set; }
        public virtual ICollection<sales> sales { get; set; }
    }
}
