//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_Murtazin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class rfid_cash_collections
    {
        public string vending_machine_id { get; set; }
        public string rfid_cash_collection { get; set; }
        public string notes { get; set; }
        public string location { get; set; }
        public string work_mode { get; set; }
    
        public virtual vending_machines vending_machines { get; set; }
        public virtual work_modes work_modes { get; set; }
    }
}
