//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_Murtazin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class rfid_services
    {
        public string vending_machine_id { get; set; }
        public string rfid_service { get; set; }
        public string coordinates { get; set; }
        public string total_income { get; set; }
        public string timezone { get; set; }
    
        public virtual vending_machines vending_machines { get; set; }
    }
}
