//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_Murtazin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class rfid_loading
    {
        public string vending_machine_id { get; set; }
        public string rfid_loading1 { get; set; }
        public string model { get; set; }
    
        public virtual vending_machines vending_machines { get; set; }
    }
}
