//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_Murtazin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales
    {
        public double sales_id { get; set; }
        public string timestamp { get; set; }
        public string product_id { get; set; }
        public string total_price { get; set; }
        public Nullable<double> quantity { get; set; }
        public string payment_method { get; set; }
    
        public virtual payment_methods payment_methods { get; set; }
        public virtual product product { get; set; }
    }
}
