//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_Murtazin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.kit_online_id = new HashSet<kit_online_id>();
            this.kit_online_id1 = new HashSet<kit_online_id>();
            this.maintenance = new HashSet<maintenance>();
        }
    
        public string user_id { get; set; }
        public string email { get; set; }
        public string full_name { get; set; }
        public string is_manager { get; set; }
        public string is_engineer { get; set; }
        public string phone { get; set; }
        public string is_operator { get; set; }
        public string role { get; set; }
        public string image { get; set; }
        public string passsword { get; set; }
        public string salt { get; set; }
    
        public virtual ICollection<kit_online_id> kit_online_id { get; set; }
        public virtual ICollection<kit_online_id> kit_online_id1 { get; set; }
        public virtual ICollection<maintenance> maintenance { get; set; }
        public virtual roles roles { get; set; }
    }
}
