//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_Murtazin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class vending_machines
    {
        public vending_machines()
        {
            this.kit_online_id1 = new HashSet<kit_online_id>();
            this.maintenance = new HashSet<maintenance>();
            this.product = new HashSet<product>();
            this.rfid_cash_collections = new HashSet<rfid_cash_collections>();
            this.rfid_loading1 = new HashSet<rfid_loading>();
            this.rfid_services = new HashSet<rfid_services>();
        }
    
        public string vending_machine_id { get; set; }
        public Nullable<double> serial_number { get; set; }
        public string name { get; set; }
        public string user_id { get; set; }
        public string rfid_cash_collection { get; set; }
        public string rfid_loading { get; set; }
        public string kit_online_id { get; set; }
        public string rfid_service { get; set; }
        public string install_date { get; set; }
        public string place { get; set; }
        public string @operator { get; set; }
        public string technician { get; set; }
        public string last_maintenance_date { get; set; }
    
        public virtual ICollection<kit_online_id> kit_online_id1 { get; set; }
        public virtual ICollection<maintenance> maintenance { get; set; }
        public virtual operators operators { get; set; }
        public virtual ICollection<product> product { get; set; }
        public virtual ICollection<rfid_cash_collections> rfid_cash_collections { get; set; }
        public virtual ICollection<rfid_loading> rfid_loading1 { get; set; }
        public virtual ICollection<rfid_services> rfid_services { get; set; }
    }
}
