//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_Murtazin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class work_modes
    {
        public work_modes()
        {
            this.rfid_cash_collections = new HashSet<rfid_cash_collections>();
        }
    
        public string work_mode { get; set; }
    
        public virtual ICollection<rfid_cash_collections> rfid_cash_collections { get; set; }
    }
}
