//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP_Murtazin.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class work_descriptions
    {
        public work_descriptions()
        {
            this.maintenance = new HashSet<maintenance>();
        }
    
        public string work_description { get; set; }
    
        public virtual ICollection<maintenance> maintenance { get; set; }
    }
}
